### ISSUE TITLE
pytorch implementation

### ISSUE THREAD

**Issue by duyuanchao** [nixingyang/AdaptiveReID#10]
I have  re-implemented adaptive-l2-regularization in pytorch, [adaptive-l2-regularization-pytorch](https://github.com/duyuanchao/adaptive-l2-regularization-pytorch)

**Comment by nixingyang** [comment]
Thanks for your contribution. I have included your repository in the README file.
Xingyang

**Comment by duyuanchao** [comment]
thank you
