### ISSUE TITLE
ValueError: axes don't match array

### ISSUE THREAD

**Issue by sakshi4321** [nixingyang/AdaptiveReID#11]
Hi,
I am getting the ValueError : axes don't match array when i am trying to load the pretrained model .
I am not sure what is causing that error since there are 0 trainable params.

**Comment by nixingyang** [comment]
Hi,
It's weird that you encountered this issue. Are you using your own snippet?
Alternatively, you could check https://github.com/nixingyang/AdaptiveL2Regularization/issues/3.
All the best.
Xingyang Ni

**Comment by sakshi4321** [comment]
Thank you .The reference was very helpful.
