### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Shehla-noor** [nixingyang/AdaptiveReID#12]
@nixingyang Could you please upload pre-trained model along with weights?
Thank you in advance.

**Comment by nixingyang** [comment]
Please check the [Model Zoo](https://github.com/nixingyang/AdaptiveL2Regularization#model-zoo) section.
All the best.
Xingyang

**Comment by Shehla-noor** [comment]
> Please check the [Model Zoo](https://github.com/nixingyang/AdaptiveL2Regularization#model-zoo) section.
> All the best.
> Xingyang

Thank you.

**Comment by Shehla-noor** [comment]
Hi!
@nixingyang I want to use your model as a feature extractor for DukeMTMC-reID. When I tried to load the model using:

```
from keras.models import load_model 
AdaptiveL2Regularization = load_model('/content/gdrive/DukeMTMC_reID_ResNet50_9502036.h5', custom_objects={"AdaptiveL1L2": AdaptiveL1L2})
```

I am getting this error:
```
ValueError: Layer #0 (named "resnet" in the current model) was found to correspond to layer resnet in the save file. However the new layer resnet expects 6 weights, but the saved weights have 10 elements.
``` 
What is the reason? Am I doing something wrong here?

Thank you.

**Comment by nixingyang** [comment]
This issue is expected. Kindly refer to https://github.com/nixingyang/AdaptiveL2Regularization/issues/3.
Xingyang

**Comment by Shehla-noor** [comment]
Thank you for the reference. 
@nixingyang It seems like I cannot load the model directly using ```load_model```. I have to go through all the steps mentioned in #3.
