### ISSUE TITLE
Amplitude

### ISSUE THREAD

**Issue by swingbalance** [nixingyang/AdaptiveReID#15]
Hi,
After study your paper,
I'm curious about amplitude A,
what effect could be achieved by amplitude A?
and is it a learnable parameter or a amplitude function, such as cosine function ?
I will be grateful for any help you can provide

**Comment by nixingyang** [comment]
Hi,
The amplitude A is a hyper-parameter that limits the highest possible value for L2 Regularization.
It is [a non-trainable constant value](https://github.com/nixingyang/AdaptiveL2Regularization/blob/f599463a4b5b58b22b9f72847d544224c3314363/regularizers/adaptation.py#L46-L49), and one could find the "optimal" value using hyper-parameter optimization.
All the best.
Xingyang

**Comment by swingbalance** [comment]
Thanks I got it
