### ISSUE TITLE
something wrong with distance_matrix

### ISSUE THREAD

**Issue by kazuki-can** [nixingyang/AdaptiveReID#16]
Hello again.
I've been using this model and I like this model a lot.
But I have an error that the distance matrix does not change .
I created an environment before but since the pc got broken, I moved the environment to new pc.
The code runs till the end but the distance matrix show like below.
`data/person1/person1.png and data/person2/person2.png
distance[[0.00812232,0.05873889]]
data/person2/person2.png and data/person3/person3.png
distance[[0.00845033,0.0598461 ]]
data/person3/person3.png and data/person4/person4.png
distance[[0.00839752,0.05975628 ]]
data/person4/person4.png and data/person5/person5.png
distance[[0.00839752,0.05975628 ]]
data/person5/person5.png and data/person6/person6.png
distance[[0.00839752,0.05975628 ]]
data/person6/person6.png and data/person7/person7.png
distance[[0.00839752,0.05975628 ]]
`   
The first distance always is about 0.008~ and the second distance always is about 0.05~.
How can I sort this out?
Thank you.

**Comment by nixingyang** [comment]
Hi,
Have you made modifications to the original scripts? If so, please post a minimal snippet that would reproduce this issue.
All the best.
Xingyang

**Comment by kazuki-can** [comment]
This is what I added to the original code.
`        print("Freezing the whole model in the evaluation_only mode ...")
         training_model.trainable = False
         training_model.compile(**training_model.compile_kwargs)
         people_list =[
            'custom_database/index0/img00063.png',
            'custom_database/index7/img00006.png',
            'custom_database/index0/img00071.png',
            'custom_database/index7/img00017.png',
            'custom_database/index0/img00077.png',
            'custom_database/index7/img00026.png',
            'custom_database/index0/img00084.png',
            'custom_database/index8/img00019.png'
            
        ]
        for i in range(6):
            
            image_content_list = [
                read_image_file(image_file_path, input_shape)
                for image_file_path in [
                    people_list[i],
                    people_list[i+1],
                    people_list[i+2]
                ]
            ]
            image_content_array = preprocess_input(np.array(image_content_list))
            first, second, third = inference_model.predict(image_content_array,batch_size=batch_size)
            distance_matrix = test_evaluator_callback.compute_distance_matrix(
                query_image_features=[first],
                gallery_image_features=[second, third],
                metric="cosine",
                use_re_ranking=use_re_ranking)
            print(f'People{people_list[i]},{people_list[i+1]},{people_list[i+2]}')
            print(f'ditance_list{distance_matrix}')
             `
I got results like below.
`Peoplecustom_database/index0/img00063.png,custom_database/index7/img00006.png,custom_database/index0/img00071.png
ditance_list[[0.00812232 0.05873889]]
Peoplecustom_database/index7/img00006.png,custom_database/index0/img00071.png,custom_database/index7/img00017.png
ditance_list[[0.00845033 0.0598461 ]]
Peoplecustom_database/index0/img00071.png,custom_database/index7/img00017.png,custom_database/index0/img00077.png
ditance_list[[0.00839752 0.05975628]]
Peoplecustom_database/index7/img00017.png,custom_database/index0/img00077.png,custom_database/index7/img00026.png
ditance_list[[0.00839752 0.05975628]]
Peoplecustom_database/index0/img00077.png,custom_database/index7/img00026.png,custom_database/index0/img00084.png
ditance_list[[0.00839752 0.05975628]]
Peoplecustom_database/index7/img00026.png,custom_database/index0/img00084.png,custom_database/index8/img00019.png
ditance_list[[0.00839752 0.05975628]]
All done!`

**Comment by nixingyang** [comment]
Hi,
The snippet looks OK.
Based on my understanding, the first distance should be higher than the second distance.
You could replace one sample in `people_list` with a normal image that does not contain a person. This should at least generate a distance matrix that is different from the current one.
Xingyang

**Comment by kazuki-can** [comment]
I replaced the last picture with the picture of house, but the second value of the distance_matrix did not change.
How can I sort this out?

**Comment by nixingyang** [comment]
Hi,
I tested the following snippet which worked as expected, i.e., values in `distance_matrix` were different.

```python
import glob
image_file_path_list = sorted(
    glob.glob("/home/*/Pictures/*"))
image_content_list = [
    read_image_file(image_file_path,
                    test_evaluator_callback.input_shape)
    for image_file_path in image_file_path_list
]
image_content_array = np.array(image_content_list)
image_content_array = test_evaluator_callback.preprocess_input(
    image_content_array)
feature_array = inference_model.predict(x=image_content_array,
                                        batch_size=batch_size)
distance_matrix = test_evaluator_callback.compute_distance_matrix(
    query_image_features=feature_array,
    gallery_image_features=feature_array,
    metric="cosine",
    use_re_ranking=False)
print(distance_matrix)
```

If you still have this issue, you may debug the snippet line by line and check whether there are warning/error messages.
All the best.
Xingyang

**Comment by kazuki-can** [comment]
Is is possible to show up this issue by what I use Windows OS?

**Comment by nixingyang** [comment]
It's hard to say. Debugging the code would help in identifying the root cause.
Xingyang

**Comment by kazuki-can** [comment]
Hello again.
I've been debugging so far, but I still have the same problem.
Even though I set different pictures as test images, it gives me the same distance matrix.
Do I have to add or change the original code by my PC?
I tried this mode on both Windows and Linux.

This is my PC environment.
Intel Core i9-11900K
RAM 64 GB
Windows 10 Pro
GPU NVIDIA GeForce RTX 3090

To use this model on Windows, I changed "long" to "long long" in "metrics/rank_cy.pyx".
I changed './datasets/__init__.py' to set the root_folder_path , but since I put Market1501 in AdaptiveL2Regularization folder, I set './' as root_folder_path.

**Comment by nixingyang** [comment]
Hi,
I suggest running the [evaluation](https://github.com/nixingyang/AdaptiveL2Regularization#evaluation) procedure without any modifications. This should give scores that are consistent with our paper.
Afterward, you may add your own changes one by one and check whether it affects the scores or not.
On a side note, the scores in evaluation would be incorrect if `distance_matrix` is wrong.
All the best.
Xingyang Ni

**Comment by kazuki-can** [comment]
So do you mean I don't have to change the code depending on pc?

**Comment by nixingyang** [comment]
The idea is to replicate the evaluation procedure using the provided repository as it is. You may need to specify the `root_folder_path` argument manually, but no other modifications are required (at least on Linux).
Xingyang

**Comment by kazuki-can** [comment]
![image](https://user-images.githubusercontent.com/52147081/123411385-5da41f80-d5eb-11eb-91cc-ec9a040e3512.png)
I think this is too low mAP.
I downloaded the pre-trained model from your git repository and used it.
Is this correct ?

**Comment by nixingyang** [comment]
No, it doe not make sense. Ideally, one should be able to reproduce the results reported in our paper.
Please check whether there are warning/error messages.
Xingyang

**Comment by kazuki-can** [comment]
I also tried it on Ubuntu 18.04 and it says this below.
`test_cosine_False_1_rank_to_accuracy_dict rank-1 accuracy 0.000000
test_cosine_False_1_rank_to_accuracy_dict rank-5 accuracy 0.000000
test_cosine_False_1_rank_to_accuracy_dict rank-10 accuracy 0.000000
test_cosine_False_1_rank_to_accuracy_dict rank-20 accuracy 0.000594
test_cosine_False_1_mAP_score 0.001111
`
I checked the output and it says `W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code 65280, output: ptxas fatal   : Value 'sm_86' is not defined for option 'gpu-name'`
Only this sentence has "W tensorflow" so I thought this causes this problem.

**Comment by nixingyang** [comment]
You may add the full command that you are using and attach the complete log of the command. I could check those.
As a side note, make sure that you are following the guide in the [environment](https://github.com/nixingyang/AdaptiveL2Regularization#environment) section.
Xingyang

**Comment by kazuki-can** [comment]
This is the full command I use.
`python -u solution.py --dataset_name "Market1501" --backbone_model_name "ResNet50" --pretrained_model_file_path "Market1501_ResNet50_9502037.h5" --output_folder_path "evaluation_only" --evaluation_only --freeze_backbone_for_N_epochs 0 --testing_size 1.0 --evaluate_testing_every_N_epochs 1 --workers 1 `
Is it possible that it doesn't show the correct results since my new pc has initial failure?
I pasted the txt file that says the log of the command.
Thank you for spending your time on my error a lot.
[adaptivel2_log_windows.txt](https://github.com/nixingyang/AdaptiveL2Regularization/files/6720936/adaptivel2_log_windows.txt)

**Comment by kazuki-can** [comment]
[adaptivel2_log_ubuntu18_04.txt](https://github.com/nixingyang/AdaptiveL2Regularization/files/6720966/adaptivel2_log_ubuntu18_04.txt)
And this is the log on Linux(Ubuntu18.04)

**Comment by nixingyang** [comment]
Hi,

- The full command is OK. For clarity, I would use `python3` rather than `python`.
- Make sure that the scripts are not modified. Please check the output of `git status`.
- It appears that you have the dataset saved under `~/Documents/AdaptiveL2Regularization/Market-1501-v15.09.15`. Please verify that no changes are made.
- For your reference, this is the [slurm-18758240.log](https://github.com/nixingyang/AdaptiveL2Regularization/files/6721326/slurm-18758240.log) file in my experiment, and the results are correct. I don't have the "Internal: ptxas exited with non-zero error code 65280" issue. You may search for it under the repository of TensorFlow.
- The loss values (e.g., `activation_loss` and `lambda_loss`) in your log are excessively high. Although these values are not indicative, this might be related to the current problem.

Xingyang

**Comment by kazuki-can** [comment]
- When I use `python3` instead of `python`, it doesn't run.
- I have the dataset in `~/Documents/AdaptiveL2Regularization/Market-1501-v15.09.15`.
- Just in case, could you paste your environment yaml file here? I want to try it on the same environment as yours.

**Comment by kazuki-can** [comment]
I also think this causes by my broken pc so I want to try this model on Google Colab.
But I got an error below
`Use /content/drive/My Drive/AdaptiveL2Regularization as root_folder_path ...
Traceback (most recent call last):
  File "solution.py", line 1070, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "solution.py", line 842, in main
    load_accumulated_info_of_dataset(root_folder_path=root_folder_path, dataset_name=dataset_name)
  File "/content/drive/MyDrive/AdaptiveL2Regularization/datasets/__init__.py", line 48, in load_accumulated_info_of_dataset
    root_folder_path=root_folder_path)
  File "/content/drive/MyDrive/AdaptiveL2Regularization/datasets/market1501.py", line 65, in load_Market1501
    image_folder_name="bounding_box_train")
  File "/content/drive/MyDrive/AdaptiveL2Regularization/datasets/market1501.py", line 25, in _load_accumulated_info
    assert len(image_file_path_list) == 12936
AssertionError`
It seems that I don't have datas in the dataset directory, but I download market1501 and unzipped it .
How can I solve this ?

**Comment by nixingyang** [comment]
Using `python3` should definitely work. Something is wrong with your environment. Please follow the [environment](https://github.com/nixingyang/AdaptiveL2Regularization#environment) section, and check [TensorFlow2.2.yml.txt](https://github.com/nixingyang/AdaptiveL2Regularization/files/6724279/TensorFlow2.2.yml.txt).
Regarding the assertion error, make sure that you have those folders (e.g., bounding_box_train and bounding_box_test) under `root_folder_path/Market-1501-v15.09.15`.
Xingyang

**Comment by kazuki-can** [comment]
I tried many ways to sort this out, but I found a website that says RTX3090 is not compatible with CUDA10.X.
Is there any way to use this model with CUDA11.0 and Tensorflow==2.4 or CUDA11.3 and Tensorflow==2.5?

**Comment by nixingyang** [comment]
Glad to hear that you have found a plausible explanation for this issue. To my knowledge, NVIDIA A100 can not run on CUDA 10 with PyTorch.
I have experienced with TensorFlow 2.3 and 2.4 before. However, there were some tricky bugs, e.g., [issue 41021](https://github.com/tensorflow/tensorflow/issues/41021). As a result, I decided to stick with TensorFlow 2.2.
On the one hand, you may try to fix bugs after updating TensorFlow. On the other hand, you may consider using [FlipReID](https://github.com/nixingyang/FlipReID) instead. I might already have fixed those issues.
Xingyang

**Comment by kazuki-can** [comment]
Thank you for your advice to me.
It will surely help me a lot.
Now, I consider using FlipReID and I have created the environment, so I will ask you one question in the repository.
