### ISSUE TITLE
Regarding Global and Local Branches as Mentioned in Paper

### ISSUE THREAD

**Issue by shreejalt** [nixingyang/AdaptiveReID#18]
Hi @nixingyang 

Can you point me to the piece of code where you make local and global branches as mentioned in the paper?

I am unable to find the same

**Comment by nixingyang** [comment]
Please check this [snippet](https://github.com/nixingyang/AdaptiveL2Regularization/blob/8606d0ed9d2f28d590a3b3e0ef521d15f2240556/solution.py#L248-L291).
Xingyang
