### ISSUE TITLE
Does it support evaluation AP mAP rank k on dataset? 

### ISSUE THREAD

**Issue by TCHeish** [nixingyang/AdaptiveReID#2]

**Comment by nixingyang** [comment]
Hi,
Thanks for your interest in our work.
Following the practice of previous works, we report the mAP scores and the rank-1 accuracies.
Please check the [compute_CMC_mAP](https://github.com/nixingyang/AdaptiveReID/blob/c9a2ee075f5ae9c1144262a84e8a85e1a5cfe1db/evaluation/metrics/__init__.py#L11) function for more details.
All the best.
Xingyang
