### ISSUE TITLE
Multiprocessing deadlock 

### ISSUE THREAD

**Issue by thanit456** [nixingyang/AdaptiveReID#4]
![Annotation 2020-09-06 223003](https://user-images.githubusercontent.com/35522239/92329265-9db40900-f090-11ea-986e-d994ded30b05.png)
How can I solve this problem?

**Comment by nixingyang** [comment]
Hi,
Thanks for your interest in this work.
Our implementation has only been tested on Linux. If you still encounter such issue while following the instructions in the [Environment](https://github.com/nixingyang/AdaptiveReID#environment) section, please consider switching to Linux. IMHO, Windows is not an ideal option for research on deep learning.
As a side note, the error message shown in your screenshot looks suspicious. If the program fails for some reason, the error should come from a Python script inside the conda environment, e.g., "conda_directory/envs/environment_name".
All the best.
Xingyang
