### ISSUE TITLE
How to visualize the embedding space

### ISSUE THREAD

**Issue by kazuki-can** [nixingyang/AdaptiveReID#9]
Thank you for helping me a lot before.
I try to use this model  on custom dataset now.
I could have already evaluated on custom dataset, thanks to a closed issue.
But I want to see the embedding space about my dataset.

Is it possible to visualize the embedding space on custom dataset?

Thank you.

**Comment by nixingyang** [comment]
Yes. Once you get the features, you can easily visualize them using methods such as [PCA + t-SNE](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html).
Xingyang

**Comment by kazuki-can** [comment]
Thank you very much.
I'll try that.

**Comment by kazuki-can** [comment]
I tried to visualize the embedding space by plt from matplotlib. But I got an warning below. 
solution.py:1069: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
How can I visualize it in a different way ?

**Comment by nixingyang** [comment]
This is due to [matplotlib.use("Agg")](https://github.com/nixingyang/AdaptiveL2Regularization/blob/f599463a4b5b58b22b9f72847d544224c3314363/callbacks/__init__.py#L11). You could either comment out that line or save the figure directly to disk without showing it.
Xingyang

**Comment by kazuki-can** [comment]
Thank you so much.
I could save it but I did it on 'distance_matrix'.
Is it correct to visualize the variable?
If it's not ,what is the name of variable that has embedding space to visualize the embedding space?

**Comment by nixingyang** [comment]
Use `query_image_features` and `gallery_image_features`.
Xingyang

**Comment by kazuki-can** [comment]
`       distance_array = np.empty((0,4096), float)
	image_file_path_list = [
            os.path.join(dataset_folder_path, item) for item in [
                basic_person,
                people[0],
                people[3]
            ]
        ]
        image_content_list = [
            read_image_file(image_file_path, input_shape)
            for image_file_path in image_file_path_list
        ]
        image_content_array = preprocess_input(np.array(image_content_list))

        first, second, third = inference_model.predict(image_content_array,
                                                        batch_size=batch_size)
        distance_matrix,qif,gif = test_evaluator_callback.compute_distance_matrix(
            query_image_features=[first],
            gallery_image_features=[second, third],
            metric="cosine",
            use_re_ranking=use_re_ranking)
        distance_array = np.append(distance_array, qif, axis=0)
        distance_array = np.append(distance_array, gif, axis=0)
        q_space = TSNE(n_components=2).fit_transform(distance_array)
        fig = plt.figure()
        plt.plot(q_space,'o')
        plt.title('Embedding Space')
        plt.grid()
        fig.savefig('embedding_space.png')`

![embedding_space](https://user-images.githubusercontent.com/52147081/105481734-cdd01180-5cea-11eb-8453-cf0d05b7ebd8.png)
I changed the code like above and got the picture.
But I don't think what I've done is right.
Is this correct to visualize the embedding space?

basic_person,people[0] and people[3] are the path to each image.
qif:query_image_features
gif:gallery_image_features

**Comment by nixingyang** [comment]
Visualize `feature_array` (returned by `inference_model.predict`), rather than `distance_array`.
Also, it might be useful to apply PCA beforehand, as mentioned in [here](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html).
Xingyang

**Comment by kazuki-can** [comment]
`image_file_path_list = [
            os.path.join(dataset_folder_path, item) for item in [
                basic_person,
                people[0],
                people[3]
            ]
        ]
        image_content_list = [
            read_image_file(image_file_path, input_shape)
            for image_file_path in image_file_path_list
        ]
        image_content_array = preprocess_input(np.array(image_content_list))

        first, second, third = inference_model.predict(image_content_array,
                                                        batch_size=batch_size)
        feature_array = [first,second,third]
        distance_matrix = test_evaluator_callback.compute_distance_matrix(
            query_image_features=[first],
            gallery_image_features=[second, third],
            metric="cosine",
            use_re_ranking=use_re_ranking)

        q_space = TSNE(n_components=2).fit_transform(feature_array)
        fig = plt.figure()
        plt.plot(q_space,'o')
        plt.title('Embedding Space')
        plt.grid()
        fig.savefig('embedding_space.png')`
![embedding_space](https://user-images.githubusercontent.com/52147081/105571890-ee55a580-5d96-11eb-9b0b-390239261123.png)

Is this what you meant?
people[3] is the same person as basic_person.

**Comment by nixingyang** [comment]
Before applying t-SNE, it is advised to map the feature vectors to a lower-dimensional space (e.g., 64). Please check the documentation of [t-SNE](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html).
Xingyang

**Comment by kazuki-can** [comment]
`image_file_path_list = [
            os.path.join(dataset_folder_path, item) for item in [
                basic_person,
                people[1],
                people[3]
            ]
        ]
        image_content_list = [
            read_image_file(image_file_path, input_shape)
            for image_file_path in image_file_path_list
        ]
        image_content_array = preprocess_input(np.array(image_content_list))

        first, second, third = inference_model.predict(image_content_array,batch_size=batch_size)

        distance_matrix = test_evaluator_callback.compute_distance_matrix(
            query_image_features=[first],
            gallery_image_features=[second, third],
            metric="cosine",
            use_re_ranking=use_re_ranking)

        feature_array = [first.reshape(-1,64),second.reshape(-1,64),third.reshape(-1,64)]
        num = range(len(feature_array))
        colors = ['b','g','r']
        fig = plt.figure()
        for feature_element,i in zip(feature_array,num):
            maker = '$' + str(i+1) + '$'
            X = PCA(n_components=64).fit_transform(feature_element)
            q_space = TSNE(n_components=2).fit_transform(X)
            plt.plot(q_space,'o',color=colors[i])
        
        plt.title('Embedding Space')
        plt.grid()
        fig.savefig('embedding_space.png')`
![embedding_space](https://user-images.githubusercontent.com/52147081/105818121-d893ea80-5ff9-11eb-8aee-fcfd2ed1ad2a.png)

I used PCA  to reduce the dimention of each feature  like above and used TSNE, but I still think what I've been doing is right to visualize the embedding space.
Sorry for making you busy and thank you for explaining every time.

**Comment by nixingyang** [comment]
No problem.
Are you visualizing features of three images? If so, you should only see three dots in the figure.
This line `feature_array = [first.reshape(-1,64),second.reshape(-1,64),third.reshape(-1,64)]` does not make sense. One should use PCA to map the `[3, 4096]` array to `[3, 64]`, and use t-SNE to map the `[3, 64]` array to `[3, 2]`.
Xingyang

**Comment by kazuki-can** [comment]
`image_content_list = [
            read_image_file(image_file_path, input_shape)
            for image_file_path in image_file_path_list
        ]
        image_content_array = preprocess_input(np.array(image_content_list))

        first, second, third = inference_model.predict(image_content_array,batch_size=batch_size)

        distance_matrix = test_evaluator_callback.compute_distance_matrix(
            query_image_features=[first],
            gallery_image_features=[second, third],
            metric="cosine",
            use_re_ranking=use_re_ranking)
        
        feature_array = [first, second, third]

        #PCA [3,4096] to [3,64]
        #TSNE [3,64] to [3,2]
        pca = PCA(n_components=64).fit(feature_array)
        pca_feature = pca.transform(feature_array)
        tsne_feature = TSNE(n_components=2).fit_transform(pca_feature)

        colors = ['b','g','r']
        fig = plt.figure()
        for feature,c in zip(tsne_feature,colors):
            maker = '$' + str(i+1) + '$'
            plt.scatter(feature[0],feature[1],color=c)
        
        plt.title('Embedding Space')
        plt.grid()
        fig.savefig('embedding_space.png')`

As you advised me, I changed the code like above. But I got an error saying 
`Traceback (most recent call last):
  File "solution.py", line 1143, in <module>
    app.run(main)
  File "C:\Users\####\anaconda3\envs\AdaptiveL2\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\####\anaconda3\envs\AdaptiveL2\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "solution.py", line 1078, in main
    pca = PCA(n_components=64).fit(feature_array)
  File "C:\Users\####\anaconda3\envs\AdaptiveL2\lib\site-packages\sklearn\decomposition\_pca.py", line 351, in fit
    self._fit(X)
  File "C:\Users\####\anaconda3\envs\AdaptiveL2\lib\site-packages\sklearn\decomposition\_pca.py", line 423, in _fit
    return self._fit_full(X, n_components)
  File "C:\Users\####\anaconda3\envs\AdaptiveL2\lib\site-packages\sklearn\decomposition\_pca.py", line 442, in _fit_full
    % (n_components, min(n_samples, n_features)))
ValueError: n_components=64 must be between 0 and min(n_samples, n_features)=3 with svd_solver='full'`

How can I sort this out?

**Comment by nixingyang** [comment]
The error message `ValueError: n_components=64 must be between 0 and min(n_samples, n_features)=3 with svd_solver='full'` is self-explanatory. In this specific case, `n_samples=3`, `n_features=4096` and `n_components=64`.
This error can be easily fixed by adding more images, i.e., more than 64 - the more the merrier.
Xingyang

**Comment by kazuki-can** [comment]
I could visualize the embedding space.
Thank you very much for helping me.

**Comment by kazuki-can** [comment]
When it's training, is there any possibilities to affect the extracted features by image of background?

**Comment by nixingyang** [comment]
Could you elaborate on the question?
Xingyang

**Comment by kazuki-can** [comment]
When it's training, the model gets the feature of each image.
But every image has a background.
So, I thought that the background feature can probably affect the extracted feature.
For example, I have two pictures of the same person with same pose, same appearance and different background.

**Comment by nixingyang** [comment]
Some time ago, I tried to replace the original images with the cropped images which were generated by a segmentation model. In other words, those images only contain persons, and the background is masked out. However, it decreased the mAP scores significantly. You may search for other works on this idea.
Xingyang

**Comment by kazuki-can** [comment]
I have one more question about learning rate.
You wrote "The learning rate increases linearly from a low value to the pre-defined base learning rate in the early stage of the training procedure, and it is divided by ten once the performance on the validation set plateaus",but why do you divide it by ten at the moment?
Thank you.

**Comment by nixingyang** [comment]
It's like a common practice.
In the [AlexNet](https://papers.nips.cc/paper/2012/file/c399862d3b9d6b76c8436e924a68c45b-Paper.pdf) paper, it says "The heuristic which we followed was to divide the learning rate by 10 when the validation error rate stopped improving with the current learning rate.".
Of course, you can try learning rate schedules that are more complex, such as [cosine annealing](https://arxiv.org/abs/1608.03983).
Xingyang
